#import <PEGKit/PKParser.h>

enum {
    STORYPARSER_TOKEN_KIND_PHRASESPEC = 14,
    STORYPARSER_TOKEN_KIND_IMAGESPEC = 15,
    STORYPARSER_TOKEN_KIND_TERMINATOR = 16,
};

@interface StoryParser : PKParser

@end

