#import <PEGKit/PKParser.h>

enum {
    STORYPARSER_TOKEN_KIND_CLOSE_BRACKET = 14,
    STORYPARSER_TOKEN_KIND_OPEN_BRACKET = 15,
    STORYPARSER_TOKEN_KIND_SEMI_COLON = 16,
    STORYPARSER_TOKEN_KIND_CLOSE_CURLY = 17,
    STORYPARSER_TOKEN_KIND_OPEN_CURLY = 18,
};

@interface StoryParser : PKParser

@end

